source 'http://rubygems.org'

gem 'unicorn', '~> 3.3.1'
gem "rails", "~> 2.3.5"

gem 'mysql'
gem "inherited_resources", '1.0.2'
gem "has_scope", '0.4'
gem "responders", '0.4.2'
gem 'haml'
gem "rmagick", '2.12.2'
gem "pacecar"
gem 'unicode'
gem "i18n"
gem "ukrainian"
gem "formtastic"